### ISSUE TITLE
Emacs buffer sometimes closes, when using it to edit text in Firefox

### ISSUE THREAD

**Issue by obar** [KarimAziev/chrome-emacs#8]
The Emacs buffer will sometimes close randomly when typing in it, it's unclear how this is triggered but it looks like a few big cursor jumps in quick succession will do it, but not all of the time. A race condition perhaps?

I added a little more debugging to the elisp package as atomic-chrome-debug doesn't give any hints for this bug, and with more messages printed I see that the websocket's `:on-close` is being called. If I give the constructor an `:on-error` handler as well, that doesn't fire when this bug happens.

I can't get the same disconnection to happen when typing or moving the cursor quickly in the Firefox text area.

When debugging the extension in Firefox (about:addons > gear menu > Debug add-ons > Network tab) I can't recreate this bug anymore. I imagine the only change would be a slight delay added for that debugging, which I think further suggests a race condition as the culprit.

**Comment by dpshelio** [comment]
This has happened to me on https://hackmd.io and GitHub issues. It happened while I was writing this comment, I took a timer, and it seems it happens all the times after 30 seconds (exactly!)
I've only started using this a couple of days ago, so I can't comment on other sites.

On `*Warnings*` buffer I've got the following message: 
```
⛔ Error (websocket): in callback `on-message': could not parse JSON stream: "unable to decode byte 0xfa", "<string>", 1, 0, 0
```

However, if I start writing on Firefox while the connection with emacs is open and only seeing how the updates happen in emacs, then it doesn't stop after the first 30 seconds. But as soon as I jump to emacs, then it stops after 30 seconds. And throws the above warning.

**Comment by KarimAziev** [comment]
I also faced the issue using Firefox, and I've just pushed a possible fix that should utilize a more native approach for Firefox by using alarms instead of timers for the keep-alive procedure.

It will take a day or two for the extension review process, so I will not close this issue yet. However, I kindly ask you to check again using version 0.5.2 of Chrome-Emacs once it becomes available.

I also suspect that it is important to use the latest version of Firefox. Could you please confirm the version of Firefox you are using when you encountered this issue?

Thank you for your feedback and patience.

**Comment by KarimAziev** [comment]
Oh, it is already published. Please upgrade to version 0.5.2 and let me know if the bug still occurs.

**Comment by dpshelio** [comment]
Yep! :raised_hands:  it seems that now lasts longer than the 30 seconds I had before. I'll keep trying on other sites and report if I get the same problem again. Thanks!!

**Comment by obar** [comment]
Trying my same test but with the updated extension, I couldn't recreate the bug. Looks good @KarimAziev! Thank you.

Nice find on the 30s timing @dpshelio :)
